# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: production
    groups:
      mantine:
        patterns:
          - "@mantine/*"
      fontawesome:
        patterns:
          - "@fortawesome/*"
        exclude-patterns:
          - "@fortawesome/react-fontawesome"
      fullcalendar:
        patterns:
          - "@fullcalendar/*"
    ignore:
      - dependency-name: "@mantine/*"
        versions: [ "7.x" ] # Major rework needed for new major version
      - dependency-name: "@tanstack/react-query" # Spams too much

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
